# Generated by Django 5.2.5 on 2025-08-13 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be an Egyptian number like 010/011/012/015 + 8 digits.', regex='^(010|011|012|015)\\d{8}$')])),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
