# Generated by Django 5.2.5 on 2025-08-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicecategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='slug',
        ),
    ]
